### ISSUE TITLE
[FEATURE] - combine post and uploaded image together

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/hashtag#15]
**Description**
When a user tries to add an image, it uploads only the image, I want the user can upload both the text and image together.

**Example**
In most social media apps you can upload only the text, or upload only an image, or you can upload both, the app should be able to request both instead of uploading one at a time separately

**Additional context**
> _No response_

**Comment by helloshiv01** [comment]
please assign me this issue

**Comment by creative-tutorials** [comment]
> please assign me this issue

Okay, I'll do that right away

**Comment by creative-tutorials** [comment]
> please assign me this issue

BTW the backend is there to help you out [the backend](https://github.com/creative-tutorials/hashtag-backend)

**Comment by creative-tutorials** [comment]
> please assign me this issue

@helloshiv01 are you going to work on the issue or should I assign it to someone else

**Comment by helloshiv01** [comment]
you can assign it to someone

**Comment by creative-tutorials** [comment]
> you can assign it to someone

okay, thanks

**Comment by chibuh** [comment]
Hey, please assign me this issue. Also to login, do I need to fill a form as mentioned in the _Installation_ guidelines?

**Comment by creative-tutorials** [comment]
@chibuh also please don't forget to follow the [contribution guidelines](https://github.com/creative-tutorials/hashtag/blob/master/CONTRIBUTING.md)

**Comment by chibuh** [comment]
![image](https://user-images.githubusercontent.com/74678752/196819850-b867affb-b8ab-45d5-8db8-7986eff021ce.png)
I am getting this error _"Failed to connect to MongoDB atlas"_ . Can you please help to fix this?

**Comment by creative-tutorials** [comment]
@chibuh you're now being assigned to the #15

**Comment by creative-tutorials** [comment]
> ![image](https://user-images.githubusercontent.com/74678752/196819850-b867affb-b8ab-45d5-8db8-7986eff021ce.png)
> I am getting this error _"Failed to connect to MongoDB atlas"_ on running the [Backend Code](https://github.com/creative-tutorials/hashtag-backend). Can you please help to fix this?


For that, you'll have to create your own MongoDB atlas account and use your database, the information is credential. Is this something you'll be able to do

**Comment by creative-tutorials** [comment]
@chibuh you can also install MongoDB and use your database locally
