### ISSUE TITLE
[FEATURE] Make basic auth work

### ISSUE THREAD

**Issue by mathiasayivor** [creative-tutorials/hashtag#17]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to login to the app, this prevents testing on localhost

**Describe the solution you'd like**
Make basic auth work to enable users test the system

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by creative-tutorials** [comment]
@mathiasayivor - The Auth works. I'll deploy the API so you can better understand what's going on in the backend
