### ISSUE TITLE
[FEATURE] - Remove post input if user is not authenticated

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/hashtag#23]
### **Descriptive Info**
I've already done the basic stuff I've added a code that stores the user session once the user is authenticated, now all that is left to do is to say if the session exists InputBox should show else hide it

## **Task**

- [ ] Remove post input if user is not authenticated

**Screenshot**
> _There's no screenshot applicable_

**Comment by ABSTRAC7ION** [comment]
ok forked the project and will start working on the issue

**Comment by creative-tutorials** [comment]
@NiiVx would you like to do the honours.

**Comment by NiiVx** [comment]
@creative-tutorials  Of course! Just assign me this issue and I'll be working on that

**Comment by creative-tutorials** [comment]
> @creative-tutorials Of course! Just assign me this issue and I'll be working on that

Okay you got it

**Comment by creative-tutorials** [comment]
> @creative-tutorials Of course! Just assign me this issue and I'll be working on that

If you need help the backend you can visit [backend code](https://github.com/creative-tutorials/hashtag-backend)

**Comment by creative-tutorials** [comment]
@NiiVx also please don't forget to follow the [contribution guidelines](https://github.com/creative-tutorials/hashtag/blob/master/CONTRIBUTING.md)

**Comment by NiiVx** [comment]
@creative-tutorials sure!

**Comment by creative-tutorials** [comment]
@NiiVx How's the contribution coming along
