### ISSUE TITLE
[FEATURE] Add a Protected Route

### ISSUE THREAD

**Issue by chibuh** [creative-tutorials/hashtag#26]
**Is your feature request related to a problem? Please describe.**
Even without login, the user is able to access the home page path.

**Describe the solution you'd like**
If there is no valid "session", the web app must redirect to the login page i.e. from '**./**' to '**/login**' path.

**Describe alternatives you've considered**
Adding Protected Routes seems to be best solution.

**Additional context**

**Comment by creative-tutorials** [comment]
> **Is your feature request related to a problem? Please describe.**
> Even without login, the user is able to access the home page path.
> 
> **Describe the solution you'd like**
> If there is no valid "session", the web app must redirect to the login page i.e. from '**./**' to '**/login**' path.
> 
> **Describe alternatives you've considered**
> Adding Protected Routes seems to be best solution.
> 
> **Additional context**
> 
> 

Okay @chibuh would you like to do the honours

**Comment by creative-tutorials** [comment]
> **Is your feature request related to a problem? Please describe.** Even without login, the user is able to access the home page path.
> 
> **Describe the solution you'd like** If there is no valid "session", the web app must redirect to the login page i.e. from '**./**' to '**/login**' path.
> 
> **Describe alternatives you've considered** Adding Protected Routes seems to be best solution.
> 
> **Additional context**

@chibuh I'll look into that as quickly as possible

**Comment by chibuh** [comment]
@creative-tutorials  You can assign me this if you feel this feature is needed.

**Comment by creative-tutorials** [comment]
> > @creative-tutorials You can assign me this if you feel this feature is needed.
> 
> Okay, I'll assign it to you now

@chibuh Don't forget to follow the [**Contribution Guidelines**](https://github.com/creative-tutorials/hashtag/blob/master/CONTRIBUTING.md)

**Comment by creative-tutorials** [comment]
@chibuh How's it going
