### ISSUE TITLE
Function is being rendered twice

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/hashtag#7]
**Function is being rendered twice**
The function load page and carousel are being rendered twice, You can view it at [Ln15-of-homepage](https://github.com/creative-tutorials/hashtag/blob/master/src/components/Home/Home.tsx#L15)

**To Reproduce**
1. Route to 'http://localhost:5173/'
2. Open console to see 'carousel' logged on the console

**Screenshots**
![image](https://user-images.githubusercontent.com/68476321/194403876-757b805d-f8f2-41ad-89a5-dc5000c7849b.png)

**Comment by NiiVx** [comment]
Hello there, could you assign me this problem?

**Comment by NiiVx** [comment]
Hello there, could I be assigned to this issue ? I did one solution that i would like to share.

**Comment by creative-tutorials** [comment]
Thanks @NiiVx for the fix I really appreciate ❤️

**Comment by NiiVx** [comment]
@creative-tutorials Anytime!  A hug from Brazil and let me know if there is anything I can help with!
